# Generated by Django 5.0.2 on 2024-12-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=16)),
                ('linkedin', models.URLField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('education', models.TextField()),
                ('courses', models.CharField(blank=True, max_length=255)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('proejct', models.TextField(blank=True)),
                ('leadership', models.TextField(blank=True)),
            ],
        ),
    ]
