# Generated by Django 5.0.2 on 2024-12-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_objective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='proejct',
            new_name='project',
        ),
    ]
