# Generated by Django 5.0.2 on 2024-12-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_proejct_resume_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='project',
            new_name='projects',
        ),
    ]
