# Generated by Django 5.0.2 on 2024-12-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
