# Generated by Django 5.0.2 on 2024-12-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
