# Generated by Django 5.1.4 on 2025-02-26 08:55

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_resume_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, help_text='Comma-separated list of certifications'),
        ),
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.JSONField(blank=True, default=list, verbose_name='Work Experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub Profile'),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.TextField(blank=True, help_text='Languages you speak with proficiency levels'),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True, verbose_name='Portfolio Website'),
        ),
        migrations.AddField(
            model_name='resume',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='courses',
            field=models.TextField(blank=True, help_text='Comma-separated list of relevant courses'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.JSONField(blank=True, default=list, verbose_name='Education History'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='objective',
            field=models.TextField(verbose_name='Career Objective'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills'),
        ),
    ]
