# Generated by Django 5.1.4 on 2025-02-26 08:57

from django.db import migrations, models

def fix_json_fields(apps, schema_editor):
    Resume = apps.get_model('resume', 'Resume')
    for resume in Resume.objects.all():
        # Convert education field to valid JSON if it's not already
        if not isinstance(resume.education, list):
            resume.education = []
        
        # Convert projects field to valid JSON if it's not already
        if not isinstance(resume.projects, list):
            resume.projects = []
            
        # Convert experience field to valid JSON if it's not already
        if not isinstance(resume.experience, list):
            resume.experience = []
            
        # Convert references field to valid JSON if it's not already
        if not isinstance(resume.references, list):
            resume.references = []
            
        resume.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resume_achievements_resume_certifications_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_json_fields),
    ]
